var normalUsers = {}
normalUsers["test"]="test";
normalUsers["user1"]="dEyw";
normalUsers["user2"]="dwCA";
normalUsers["user3"]="ssIS";
normalUsers["user4"]="zxep";
normalUsers["user5"]="kXIB";
normalUsers["user6"]="BgPJ";
normalUsers["user7"]="MVak";
normalUsers["user8"]="QGsI";
normalUsers["user9"]="gpuH";
normalUsers["user10"]="zdjK";


var gamificationUsers = {};
gamificationUsers["horia"] = "horia";
gamificationUsers["fabiano"] = "fabiano";
gamificationUsers["marjan"] = "marjan";
gamificationUsers["user11"] = "mOlr";
gamificationUsers["user12"] = "TDZc";
gamificationUsers["user13"] = "RyxT";
gamificationUsers["user14"] = "uKJY";
gamificationUsers["user15"] = "fDjw";
gamificationUsers["user16"] = "GgSt";
gamificationUsers["user17"] = "GKgk";
gamificationUsers["user18"] = "sCPF";
gamificationUsers["user19"] = "gSfV";
gamificationUsers["user20"] = "HFrg";

gamificationUsers["cutKcakcfizR"] = "1";
gamificationUsers["FVHFOwjwUbqm"] = "1";
gamificationUsers["ovewzQDfuHod"] = "1";
gamificationUsers["fXyYxCDpUwFR"] = "1";
gamificationUsers["uAYrhMIPdDDe"] = "1";
gamificationUsers["aqdorOGzboop"] = "1";
gamificationUsers["mOlrTDZcRyxT"] = "1";
gamificationUsers["uKJYfDjwGgSt"] = "1";
gamificationUsers["dEywdwCAssIS"] = "1";
gamificationUsers["zxepkXIBBgPJ"] = "1";